app/urls.py
from django.urls import path
from .views import Home, Contact


urlpatterns = [
	path('', Home.as_view(), name='home'),
	path('contact/', Contact, name='contact'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

# For static and media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include(('app.urls', 'app'), namespace='app')),
]

# static and media Urls
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

skills/models.py
from django.db import models
from stdimage import StdImageField


# Create your models here.
class Skill(models.Model):
  types = (
    ('n', '----------'),
    ('s', 'Soft'),
    ('h', 'Hard'),
  )
  type_skill = models.CharField(max_length=1, choices=types, default='n')
  name = models.CharField(max_length=200)
  avatar = StdImageField(
    upload_to='img/skills/',
    variations={'thumbnail': {
      "width": 100,
      "height": 100,
      "crop": True
    }},
    null=True,
    blank=True
  )

  class Meta:
    verbose_name = "Skill"
    verbose_name_plural = "Skills"
    # ordering = ['name']

  def __str__(self):
    return f"{self.name}"

  def save(self):
    self.name = self.name.lower()
    super(Skill, self).save()

app/forms.py
from django import forms


class ContactForm(forms.Form):
  name = forms.CharField(
    label="Nombre",
    required=True,
    widget=forms.TextInput(
      attrs={
        'class': 'form-control',
        'placeholder': 'Ingrese el nombre'
      }
    ),
    min_length=5,
    max_length=100
  )
  email = forms.EmailField(
    label="Email",
    required=True,
    widget=forms.EmailInput(
      attrs={
        'class': 'form-control',
        'placeholder': 'Ingrese el email'
      }
    ),
    min_length=5,
    max_length=100
  )
  content = forms.CharField(
    label="Contenido",
    required=True,
    widget=forms.Textarea(
      attrs={
        'class': 'form-control',
        'rows': 3,
        'placeholder': 'Escribe el mensaje'
      }
    ),
    min_length=10,
    max_length=1000
  )

app/views.py
from django.shortcuts import render
from django.views import generic
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.urls import reverse

from skills.models import Skill

# Create your views here.


class Home(generic.TemplateView):
    template_name = 'app/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hard_skills'] = Skill.objects.filter(type_skill='h')
        context['soft_skills'] = Skill.objects.filter(type_skill='s')
        return context


def Contact(request):

    if request.method == "POST":
        name = request.POST.get('name', '')
        _replyto = request.POST.get('_replyto', '')
        content = request.POST.get('message', '')

        email_body = """\
		    <html>
				<head>
					<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-=1">
					<style type="text/css">
						body {font-family:Calibri,Helvetica,sans-serif; font-size:12pt; color:rgb(0,0,0)}
						div{color:rgb(63,63,63); font-family:Arial; font-size:small}
						hr{display:inline-block;}
					</style>
				</head>
				<body dir="ltr" style="text-align: justify;">
					<div id="appendonsend"></div>
						<hr tabindex="-1">
					<div>
						<h2>De: %s</h2>
						<h3>Mensaje: %s</h3>
						<h5>Email de contacto: %s</h5>
					</div>
					<br>
				</body>
			</html>
		    """ % (name, content, _replyto)
        email = EmailMessage('A new email from diegoosvaldo.me', email_body, to=[
                             'd.cruz@outlook.com', 'info@diegoosvaldo.me'])
        email.content_subtype = "html"
        email.send()
    return redirect(reverse('app:home'))

skills/views.py
from django.shortcuts import render

# Create your views here.

app/templates/app/home.html
{% extends 'bases/base.html' %}
{% load static %}

{% block content %}
<!-- Masthead -->  
{% include 'includes/masthead.html' %}

<!-- About -->  
{% include 'includes/about.html' %}

<!-- Experience -->
{% include 'includes/experience.html' %}

<!-- Skills -->
{% include 'includes/skills.html' %}

<!-- Contact -->
{% include 'includes/contact.html' %}

{% endblock content %}

app/templates/bases/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Regular data -->
    <meta charset="utf-8">
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <link rel="icon" type="image/png" href="{% static 'app/img/favicon.png' %}" sizes="64x64">
    <!-- Description -->
    <meta name="author" content="Diego Osvaldo" />
    <meta name="description" content="Freelance, Backend Developer, Passionate GIS Developer" />
    <meta name="keywords" content="diego, osvaldo, diego osvaldo, diego cruz, portfolio, backend, frontend, full stack, gis, geo, web, ux, ui, design, branding, experience, product, manager, freelance, interface, remote, developer" />
    <meta name="Resource-type" content="Document" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Open Graph data -->
    <meta property="og:site_name" content="Diego Osvaldo" />
    <meta property="og:title" content="Diego Osvaldo | Backend Developer" />
    <meta property="og:description" content="Freelance, Backend Developer, Passionate GIS Developer" />
    <meta property="og:image" content="{% static 'app/img/bg/thumbnail.jpg'%}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://diegoosvaldo.me" />
    <!-- Title -->
    <title>
        {% block title %}Diego Osvaldo | Backend Developer & Passionate GIS Developer{%endblock%}
    </title>
    <!-- Twitter -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@diegocruztorrez">
    <meta name="twitter:creator" content="@diegocruztorrez">
    <meta name="twitter:title" content="Diego Osvaldo">
    <meta name="twitter:description" content="Freelance, Backend Developer, Passionate GIS Developer">
    <meta name="twitter:url" content="https://diegoosvaldo.me">
    <meta name="twitter:image" content="{% static 'app/img/bg/thumbnail.jpg'%}">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'app/css/jquery.pagepiling.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>

<body>
    <!-- Loader -->
    <div class="loader">
        <div class="spinner">
            <div class="double-bounce1"></div>
            <div class="double-bounce2"></div>
        </div>
    </div>
    <!-- Click capture -->
    <div class="click-capture"></div>
    <!-- Navbar -->
    {% include 'includes/navbar.html' %}
    <div id="pagepiling">
        <!-- Content -->
        {% block content %}{% endblock content %}
    </div>
    <!-- Scrollbar -->
    <!-- <div class="progress-nav">
        <ul class="navbar-nav">
            <li data-menuanchor="home" class="active"></li>
            <li data-menuanchor="about"></li>
            <li data-menuanchor="experience"></li>
            <li data-menuanchor="skills"></li>
            <li data-menuanchor="contact"></li>
        </ul>
    </div> -->
    <!-- Optional JavaScript -->
    <script src="{% static 'app/js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'app/js/popper.min.js' %}"></script>
    <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
    <script src="{% static 'app/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'app/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'app/js/jquery.pagepiling.js' %}"></script>
    <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'app/js/interface.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>

</html>

app/templates/includes/about.html
{% load static %}
<section id="about" class="navbar-is-white text-white section pp-scrollable d-flex align-items-center position-absolute" style="background-image:url('{% static 'app/img/bg/bg.jpg'%}');">
    <div class="intro">
        <div class="scroll-wrap">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-6 pr-md-5 pr-lg-0">
                        <div class="text-white mb-4">About me!</div>
                        <h2 class="text-white">My name is Diego Osvaldo. I'm a <span class="text-primary">Backend Developer</span> based in Bermejo, BO.</h2>
                        <p>I started my journey as a <span class="text-primary">programmer</span> more than 20 years ago at my school, then at university and finally in real life, I currently have the privilege of working as a <span class="text-primary">freelance</span> for agencies in Argentina and the United States.</p>
                        <p>I'm <span class="text-primary">passionate</span> about new technologies and learning new things, I have some years of experience developing (sometimes designing) Websites, Apps, APIs and others digital products, mainly with <span class="text-primary">Python</span> and <span class="text-primary">Django</span> Web Framework.</p>
                    </div>
                    <div class="mt-md-0 col-md-6 col-lg-5  offset-lg-1">
                        <div class="position-relative">
                            <img class="perfil w-100" src="{% static 'app/img/about.jpg' %}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/templates/includes/contact.html
{% load static %}

<section id="contact" class="navbar-is-white text-white section pp-scrollable position-absolute"  style="background-image:url('{% static 'app/img/bg/bg.jpg'%}');">
	<div class="intro">
		<div class="scroll-wrap">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<h2 class="text-white">Contact me</h2>
						<p class="text-muted">I will help you build your brand and grow your business.</p>
						<h4 class="text-white mt-5 pt-5">
							<ion-icon class="contact-icons" name="location-outline"></ion-icon>
							Bermejo, Bolivia.
						</h4>
						<h4 class="text-white mt-5">
							<ion-icon class="contact-icons" name="mail-open-outline"></ion-icon>
							<a href="mailto:d.cruz@outlook.com">d.cruz@outlook.com</a>
						</h4>
						<h4 class="text-white mt-5 pb-5">
							<a href="https://linkedin.com/in/diegoosvaldocruz/" target="_blank">
								<ion-icon class="contact-icons mr-5" name="logo-linkedin"></ion-icon>
							</a>
							<a href="https://twitter.com/DiegoCruzTorrez" target="_blank">
								<ion-icon class="contact-icons mr-5" name="logo-twitter"></ion-icon>
							</a>
							<a href="https://github.com/doctsystems" target="_blank">
								<ion-icon class="contact-icons mr-5" name="logo-github"></ion-icon>
							</a>
						</h4>
					</div>
					<div class="col-md-5 offset-md-2">
						<h3 class="text-white mt-0">I'm ready to bring your ideas to life. <span class="text-primary">Shoot me a message.</span></h3>
						<div class="mt-5">
							<form class="js-ajax-form" action="{% url 'app:contact' %}">
								{% csrf_token %}
								<div class="form-group">
									<input type="text" name="name" id="name" class="form-control" required placeholder="Name">
								</div>
								<div class="form-group">
									<input type="email" name="_replyto" id="_replyto" class="form-control" required="" placeholder="Email *">
								</div>
								<div class="form-group">
									<textarea rows="3" name="message" id="message" class="form-control" required placeholder="Message"></textarea>
								</div>
								<div class="message" id="success-message">
									<h5 class="text-primary">Thank you so much, your message was sent successfully ...</h5>
								</div>
								<div class="message" id="error-message">
									<h5 class="text-danger">Sorry something went wrong</h5>
								</div>
								<div class="form-group mb-0">
									<button type="submit" class="btn">Send</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/templates/includes/experience.html
{% load static %}
<section id="experience" class="navbar-is-white text-white section pp-scrollable d-flex align-items-center position-absolute" style="background-image:url('{% static 'app/img/bg/bg.jpg'%}');">
    <div class="intro">
        <div class="scroll-wrap">
            <div class="container">
                <h2 class="text-white mb-0">Experience & Projects</h2>
                <div class="mt-5 pt-5">
                    <div class="carousel-experience owl-carousel">
                        <div class="experience-item">
                            <div class="row row-experience">
                                <div class="col-md-4">
                                    <a href="http://savant-tech.com/" target="_blank">
                                        <img alt="" src="{% static 'app/img/savant.jpg'%}">
                                    </a>
                                </div>
                                <div class="col-md-4 ">2021 - 2022
                                    <h3 class="my-0 text-white">Full-Stack Developer</h3>
                                    <span>Freelance - Savant-Tech, EE.UU.</span>
                                </div>
                                <div class="col-md-4">
                                    <span class="text-primary">
                                        <a href="https://eureka.diegoosvaldo.xyz/" target="_blank">Logger21</a>
                                    </span> - Time tracking app to help your team be more productive.<br>
                                </div>
                            </div>
                            <div class="row row-experience">
                                <div class="col-md-4">
                                    <a href="http://bluebamboo.com.ar/" target="_blank">
                                        <img alt="" src="{% static 'app/img/bluebamboo.png'%}">
                                    </a>
                                </div>
                                <div class="col-md-4 ">2020 - 2022
                                    <h3 class="my-0 text-white">Backend Developer</h3>
                                    <span>Freelance - Bluebamboo, Argentina.</span>
                                </div>
                                <div class="col-md-4">
                                    <span class="text-primary">
                                        <a href="http://iiep.econ.uba.ar/" target="_blank">IIEP</a>
                                    </span> - Interdisciplinary Institute of Political Economy of Buenos Aires<br>
                                    <span class="text-primary">
                                        <a href="http://mesi.webiiep.econ.uba.ar/" target="_blank">MESi</a>
                                    </span> - Economic Simulation Models<br>
                                    <span class="text-primary">
                                        <a href="http://dia.webiiep.econ.uba.ar/" target="_blank">DIA</a>
                                    </span> - Development, Innovation and Environment
                                </div>
                            </div>
                        </div>
                        <div class="experience-item">
                            <div class="row row-experience">
                                <div class="col-md-4">
                                    <a href="https://observatoriomedico.org.bo/" target="_blank">
                                        <img alt="" src="{% static 'app/img/observatorio.png'%}">
                                    </a>
                                </div>
                                <div class="col-md-4 ">2019 - 2020
                                    <h3 class="my-0 text-white">Full-Stack Developer</h3>
                                    <span>SIB, Bolivia.</span>
                                </div>
                                <div class="col-md-4">
                                    <span class="text-primary">
                                        <a href="https://observatorio.diegoosvaldo.xyz/" target="_blank">COVID/19</a>
                                    </span> - Covid Medical Observatory<br>
                                </div>
                            </div>
                            <div class="row row-experience">
                                <div class="col-md-4">
                                    <a href="http://twitter.com/doctsystems" target="_blank">
                                        <img class="exp" alt="" src="{% static 'app/img/doctsystems.png'%}">
                                    </a>
                                </div>
                                <div class="col-md-4 ">2017 - 2020
                                    <h3 class="my-0 text-white">Personal Proyects</h3>
                                    <span>Doct Systems, Bolivia.</span>
                                </div>
                                <div class="col-md-4">
                                    <span class="text-primary">
                                        <a href="https://jaguarete.diegoosvaldo.xyz/" target="_blank">JaguaShop</a>
                                    </span> - MVP ecommerce, developmented witch Python/Django<br>
                                    <span class="text-primary">
                                        <a href="" target="_blank">GeoTja</a>
                                    </span> - Project to report incidents within the city of Tarija, Bolivia.<br>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/templates/includes/masthead.html
{% load static %}
<section id="home" class="home navbar-is-white text-white pp-scrollable d-flex align-items-center section position-absolute" style="background-image:url('{% static 'app/img/bg/me.jpg'%}');" role="main">
    <div class="intro">
        <div class="scroll-wrap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-xl-5">
                        <p class=""></p>
                        <h1 class="text-white">
                            <span class="text-primary">Hello, </span>I'm Diego Osvaldo.
                        </h1>
                        <p class="">Freelance - Backend Developer - Passionate GIS Developer</p>
                        <div class="line"></div>
                        <a class="btn mt-5 text-dark" href="/media/pdf/newCV.pdf" target="_blank">Download CV</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/templates/includes/navbar.html
{% load static %}
<nav id="navbar-desctop" class="navbar navbar-desctop">
    <div class="position-relative w-100">
        <!-- Brand-->
        <a class="navbar-brand logo" href="/">
            <img id="logo" class="logo" alt="dodo" data-img1="{% static 'app/img/logo2.png' %}" data-img2="{% static 'app/img/logo.png' %}" />
        </a>
        <!-- <div class="container d-block">
            <span class="phone  my-0 d-none d-md-block">+591 72900865</span>
            <span class="email  my-0 d-none d-md-block">d.cruz@outlook.com</span>
        </div> -->
        <!-- Toggler -->
        <button class="toggler">
            <span class="toggler-icon"></span>
            <span class="toggler-icon"></span>
            <span class="toggler-icon"></span>
        </button>
    </div>
</nav>
<nav class="navbar-bottom">
    <!-- Copyright -->
    <div class="copy d-none d-sm-block">Copyright © 2021. Made with
        <ion-icon class="copy-icons" name="heart-circle-outline"></ion-icon>
    </div>
</nav>
<!-- Navbar Mobile -->
<nav class="navbar navbar-mobile">
    <ion-icon class="close" name="close-outline"></ion-icon>
    <ul class="navbar-nav navbar-nav-mobile">
        <li class="active"><a class="nav-link active" data-menuanchor="home" href="#home">Home</a></li>
        <li><a class="nav-link" data-menuanchor="about" href="#about">About</a></li>
        <li><a class="nav-link" data-menuanchor="experience" href="#experience">Experience</a></li>
        <li><a class="nav-link" data-menuanchor="skills" href="#skills">Skills</a></li>
        <li><a class="nav-link" data-menuanchor="contact" href="#contact">Contact</a></li>
    </ul>
    <!-- Social -->
    <div class="social">
        <ul class="social-icons mr-auto mr-lg-0 d-sm-block">
            <li><a class="nav-link" href="https://linkedin.com/in/diegoosvaldocruz/" target="_blank">
                    <ion-icon name="logo-linkedin"></ion-icon>
                </a>
            </li>
            <li><a href="https://twitter.com/diegocruztorrez" target="_blank">
                    <ion-icon name="logo-twitter"></ion-icon>
                </a>
            </li>
            <li><a href="https://github.com/doctsystems" target="_blank">
                    <ion-icon name="logo-github"></ion-icon>
                </a>
            </li>
        </ul>
    </div>
    <div class="navbar-mobile-footer">
        <p>Copyright © 2021. Made with
            <ion-icon class="copy-icons" name="heart-circle-outline"></ion-icon>
        </p>
    </div>
</nav>

app/templates/includes/skills.html
{% load static %}
<section id="skills" class="navbar-is-white text-white section pp-scrollable d-flex align-items-center position-absolute" style="background-image:url('{% static 'app/img/bg/bg.jpg'%}');">
    <div class="intro">
        <div class="scroll-wrap">
            <div class="container">
                <div class="row align-items-center">
                    <div class="mt-lg-0 col-md-4 mb-3">
                        <h2 class="text-white">Hard Skills</h2>
                        <p>Here are a few things I've picked up along my life.</p>
                        <div class="pt-2">
                            <div class="row-partners row align-items-center ">
                                {% for item in hard_skills %}
                                <div class="col-partner col col-6 col-sm-4 col-md-4  col-xl-3">
                                    <img class="{{ item.name }}" alt="" src="{{ item.avatar.thumbnail.url }}">
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="mt-lg-0 col-md-5 offset-md-2">
                        <h2 class="text-white">Soft Skills</h2>
                        <p class="text-muted"><i>"Optimism is the faith that leads to success. Nothing can be done without hope and trust" </i>. Helen Keller.</p>
                        <p>I am quite an optimistic person, I always try to see the positive side of things, I trust my qualities and I am not afraid of facing new challenges or changes that come my way.</p>
                        <p>Qualities or defects:
                            <ul>
                                {% for item in soft_skills %}
                                <li>
                                    <h5 class="text-white text-muted">
                                        <i class="soft-skill">{{ item.name }}</i>
                                    </h5>
                                </li>
                                {% endfor %}
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>